# Generated by Django 3.0.3 on 2022-04-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location_city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='location_country',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
