# Generated by Django 3.0.3 on 2022-05-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_auto_20220501_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
