# Generated by Django 3.0.3 on 2022-05-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_listingoffer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_images'),
        ),
    ]
