# Generated by Django 3.0.3 on 2022-05-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0011_auto_20220520_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
