# Generated by Django 3.0.3 on 2022-05-22 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0012_auto_20220520_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoffer',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliverypayment',
            name='name',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.CreateModel(
            name='RequestDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.DeliveryPayment')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation.ListingOffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
