# Generated by Django 3.0.3 on 2022-05-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0013_auto_20220522_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypayment',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
