# Generated by Django 3.0.3 on 2022-05-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0014_auto_20220522_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestDonation',
        ),
    ]
