# Generated by Django 3.0.3 on 2022-05-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0015_delete_requestdonation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryPayment',
            new_name='WhoPays',
        ),
        migrations.RenameField(
            model_name='listingoffer',
            old_name='delivery_payment',
            new_name='who_pays',
        ),
    ]
