# Generated by Django 3.0.3 on 2022-05-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0016_auto_20220522_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whopays',
            options={'verbose_name_plural': 'Who Pays'},
        ),
        migrations.RenameField(
            model_name='listingoffer',
            old_name='price',
            new_name='delivery_cost',
        ),
    ]
