# Generated by Django 3.0.3 on 2022-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_auto_20220522_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoffer',
            name='claimed_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
