# Generated by Django 3.0.3 on 2022-05-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_listingoffer_claimed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingoffer',
            name='claimed_time',
        ),
    ]
