# Generated by Django 3.0.3 on 2022-05-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0019_remove_listingoffer_claimed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingoffer',
            name='claimed_time',
            field=models.DateTimeField(null=True),
        ),
    ]
