# Generated by Django 3.0.3 on 2022-06-02 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0023_auto_20220531_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReceivedDonation',
        ),
    ]
