# Generated by Django 4.0.4 on 2022-06-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0027_auto_20220604_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
