# Generated by Django 4.0.4 on 2022-07-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0028_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(default='Girl', max_length=30),
        ),
        migrations.AlterField(
            model_name='whopays',
            name='name',
            field=models.CharField(default='Willing to pay for delivery', max_length=200),
        ),
    ]
