# Generated by Django 4.0.4 on 2022-07-09 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0030_alter_listingoffer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='images',
            field=models.FileField(blank=True, default='images/default.jpg', upload_to='images'),
        ),
    ]
