# Generated by Django 4.0.4 on 2022-07-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0031_alter_listingoffer_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
