# Generated by Django 4.0.4 on 2022-07-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0033_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=5),
        ),
        migrations.AlterField(
            model_name='listingoffer',
            name='images',
            field=models.FileField(blank=True, default='images/listing_default.jpg', upload_to='images'),
        ),
    ]
