# Generated by Django 4.0.4 on 2022-08-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0035_alter_gender_name_alter_whopays_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingoffer',
            old_name='delivery_cost',
            new_name='shipping_cost',
        ),
    ]
