# Generated by Django 4.0.4 on 2022-10-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0036_rename_delivery_cost_listingoffer_shipping_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='listingoffer',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('claimed', 'claimed'), ('pending', 'pending'), ('removed', 'removed')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='listingoffer',
            name='who_pays',
            field=models.CharField(choices=[('Donor', 'Willing to pay for delivery'), ('Other', 'Need a sponsor')], default='Paying', max_length=30),
        ),
        migrations.DeleteModel(
            name='WhoPays',
        ),
    ]
