# Generated by Django 4.0.4 on 2022-10-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0037_payment_listingoffer_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Transaction',
        ),
    ]
