# Generated by Django 3.0.3 on 2024-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0038_rename_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
