# Generated by Django 3.0.3 on 2024-01-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0039_auto_20240102_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingoffer',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
