# Generated by Django 3.0.3 on 2024-04-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0040_auto_20240103_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
